import React from 'react'

const ProjectDetails = (props) => {
    console.log('props generated by react router => ', props); // props is automatically attached by React Router!
    
    const id = props.match.params.id;

    return (
        <div className="container section project-details">
            <div className="card z-depth-0">
                <div className="card-content">
                    <span className="card-title">Project Title - {id}</span>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quis culpa provident alias nostrum ut aspernatur, illo dicta. Ducimus sunt nisi natus at unde? Ipsa asperiores repudiandae quis laborum tempora nesciunt?</p>
                </div>
                <div className="card-action grey lighten-4 grey-text">
                    <div>Posted by The Net Ninja</div>
                    <div>2nd September, 2am</div>
                </div>
            </div>
        </div>
    )
}

export default ProjectDetails;
